import os
import requests
import time
import json
import re

import time
import json
from mistralai.client import Mistral # Install via: pip install mistralai


def generate_with_ollama(prompt: str, model_name: str = "mistral-large-latest"):
    t0 = time.time()
    api_key = "zcWIb2eyyetVl2rj5Qqw1FfBm9w03Fp2"
    
    client = Mistral(api_key=api_key,timeout_ms=120000)

    try:
        chat_response = client.chat.complete(
            model=model_name,
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
            response_format={"type": "json_object"} # Force JSON
        )
        text = chat_response.choices[0].message.content
        print(f"[LOG] Raw LLM Output: {text[:100]}...")
        return text, time.time() - t0
    except Exception as e:
        print(f"[ERROR] SDK Call failed: {str(e)}")
        return f"[infer_error] {str(e)}", time.time() - t0

def generate_with_model(prompt: str, model_name: str = "mistral-large-latest"):
    """
    Unified function used by analyzer.py.
    """
    # Use the corrected function above
    return generate_with_ollama(prompt, model_name=model_name)

def extract_json_from_text(text: str):
    """
    Attempt to safely extract a JSON object from text generated by model.
    """
    # 1. Try direct JSON
    try:
        return json.loads(text)
    except Exception:
        pass

    # 2. Try to find the first { ... } block
    m = re.search(r'(\{.*\})', text, re.S)
    if m:
        candidate = m.group(1)
        try:
            return json.loads(candidate)
        except Exception:
            # Fallback to fix common syntax issues
            fixed = candidate.replace("'", '"')
            fixed = re.sub(r",\s*}", "}", fixed)
            fixed = re.sub(r",\s*]", "]", fixed)
            try:
                return json.loads(fixed)
            except Exception:
                return {"parse_error": True, "raw": text}
    
    return {"parse_error": True, "raw": text}