# infer.py
import requests
import time
import json
import re

# If you later switch backend, extend this module.
import os
import requests
import time
import json
import re

def generate_with_ollama(prompt: str, model_name: str = "open-mistral-7b"):
    """
    Unified function for Mistral AI Cloud.
    """
    t0 = time.time()
    MISTRAL_API_KEY = os.getenv("MISTRAL_API_KEY")
    url = "https://api.mistral.ai/v1/chat/completions"
    
    headers = {
        "Authorization": f"Bearer {MISTRAL_API_KEY}",
        "Content-Type": "application/json"
    }
    
    payload = {
        "model": "open-mistral-7b",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.0
    }

    try:
        r = requests.post(url, json=payload, timeout=60)
        r.raise_for_status()
        data = r.json()
        text = data['choices'][0]['message']['content']
    except Exception as e:
        text = f"[infer_error] {str(e)}"
        
    return text, time.time() - t0

def generate_with_model(prompt: str, model_name: str = "mistral"):
    """
    Unified function used by analyzer.py.
    """
    return generate_with_ollama(prompt, model=model_name)

def extract_json_from_text(text: str):
    """
    Attempt to safely extract a JSON object from text generated by model.
    Returns a dict if parse succeeds, otherwise returns a dict with parse_error and raw.
    """
    # first try direct JSON
    try:
        return json.loads(text)
    except Exception:
        pass

    # Try to find the first { ... } block (non-greedy-ish)
    m = re.search(r'(\{(?:[^{}]|(?R))*\})', text, re.S)
    if m:
        candidate = m.group(1)
        try:
            return json.loads(candidate)
        except Exception:
            # as a fallback attempt to fix common issues (single quotes, trailing commas)
            fixed = candidate.replace("'", '"')
            fixed = re.sub(r",\s*}", "}", fixed)
            fixed = re.sub(r",\s*]", "]", fixed)
            try:
                return json.loads(fixed)
            except Exception:
                return {"parse_error": True, "raw": text}
    # If no json-like structure at all
    return {"parse_error": True, "raw": text}
